package calculator

import (
	"time"
)

// FlagData storing the flag values. You have to initialize your flags here like this:
//
//	type FlagData struct {
//			MongoURI string `json:"mongo_uri"`
//		}
//
// After initializing your flags here, put this file near your autogenerated files and use it in your project.
type FlagData struct {
	// Example: MongoURI string `json:"mongo_uri"`
	MongoURI  string        `json:"mongo_uri"`
	SleepTime time.Duration `json:"sleep_time"`
}

type CRPCConfig struct {
	FlagData        *FlagData
	IsStaging       bool
	ServiceName     string
	ControlPlaneURL string
}
