package calculator

// FlagData storing the flag values. You have to initialize your flags here like this:
//
//	type FlagData struct {
//			MongoURI string `json:"mongo_uri"`
//		}
//
// After initializing your flags here, put this file near your autogenerated files and use it in your project.
type FlagData struct {
	// Example: MongoURI string `json:"mongo_uri"`
	MongoURi string `json:"mongo_uri"`
}

type CRPCConfig struct {
	FlagData      *FlagData
	IsStaging     bool
	ServiceName   string
	AdminPanelURL string
}
